# Generated by Django 3.1.7 on 2021-09-16 07:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baravi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Roll_no',
            field=ckeditor.fields.RichTextField(blank=True, max_length=20, null=True),
        ),
    ]
